import React, { createContext, useState, useContext } from 'react';

const LanguageContext = createContext();

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider = ({ children }) => {
  const [language, setLanguage] = useState('EN');

  const translations = {
    EN: {
      upgradeToPro: "UPGRADE TO PRO - $29/MO",
      systemProtocol: "System Protocol",
      unlockInstitutional: "Unlock Institutional Flow Data & Custom Altcoin Radar",
      iAgree: "I agree to the Terms of Service & understand this is 'As-Is' educational data.",
      methodology: "Methodology",
      fieldManual: "Field Manual",
      lastSweep: "Last Sweep",
      radarStatus: "Institutional data synthesis. Do not be exit liquidity. Trade the math.",
      postureTitle: "Market Posture",
      whatItIs: "What it is:",
      howToUse: "How to use:",
      postureWhatDesc: "The AI's calculation of the macro environment based on institutional flows.",
      postureHowDesc: "Green = Safe to increase position sizing. Yellow = Reduce sizing. Red = Move to heavy cash reserves and prepare for crashes.",
      intelTitle: "Actionable Intel",
      intelWhatDesc: "Real-time synthesis of Wall Street ETF flows vs. retail sentiment.",
      intelHowDesc: "Read this before placing any trade to ensure you are trading alongside institutions, not against them.",
      intelAwaiting: "Awaiting quantitative synthesis...",
      killzoneTitle: "Kill Zone Targets",
      killzoneWhatDesc: "Algorithmic liquidation clusters where market makers hunt over-leveraged traders.",
      killzoneHowDesc: "NEVER market-buy. Place Limit Buy orders exactly at these prices to catch flash crashes at a massive discount.",
      btcCluster: "BTC Cluster",
      ethCluster: "ETH Cluster",
      solCluster: "SOL Cluster",
      encryptedData: "Encrypted Data",
      encryptedDesc: "Precision liquidity targets are restricted.",
      unlockProAccess: "Unlock Pro Access:",
      feature1: "Live BTC, ETH, & SOL Kill Zones",
      feature2: "Institutional Divergence Alerts",
      feature3: "Custom Altcoin Radar",
      radarTitle: "Custom Altcoin Radar",
      proFeature: "Pro Feature",
      whaleWatch: "Whale Watch",
      disclaimer: "DISCLAIMER: Project ARES is a data synthesis tool, not financial advice. Cryptocurrency trading carries a high risk of total loss. The developers are not liable for any trading decisions made based on this data.",
      rightsReserved: "© 2026 Project ARES. All rights reserved.",
      termsOfService: "Terms of Service",
      privacyPolicy: "Privacy Policy",
      protocolPostureDesc: "Synthesizes broad market sentiment, institutional flows, and price action to determine the current macro stance.",
      protocolKillzoneDesc: "High-probability liquidation clusters and critical technical zones where major price reactions are expected for BTC, ETH, and SOL."
    },
    KO: {
      upgradeToPro: "프로 업그레이드 - 월 $29",
      systemProtocol: "시스템 프로토콜",
      unlockInstitutional: "기관 자금 흐름 데이터 및 맞춤형 알트코인 레이더 잠금 해제",
      iAgree: "서비스 약관에 동의하며 이것이 '있는 그대로의' 교육 데이터임을 이해합니다.",
      methodology: "방법론",
      fieldManual: "현장 매뉴얼",
      lastSweep: "최근 스캔",
      radarStatus: "기관 데이터 합성. 출구 유동성이 되지 마십시오. 수학으로 거래하십시오.",
      postureTitle: "시장 태세",
      whatItIs: "설명:",
      howToUse: "사용법:",
      postureWhatDesc: "기관 흐름을 기반으로 한 AI의 거시 환경 계산.",
      postureHowDesc: "초록 = 포지션 크기 증가 안전. 노랑 = 크기 감소. 빨강 = 현금 비중 대폭 확대 및 폭락 대비.",
      intelTitle: "실행 가능한 정보",
      intelWhatDesc: "월스트리트 ETF 흐름과 개인 투자자 심리의 실시간 합성.",
      intelHowDesc: "거래를 시작하기 전에 이를 읽어 기관과 반대로 거래하지 않는지 확인하십시오.",
      intelAwaiting: "정량적 합성 대기 중...",
      killzoneTitle: "킬 존 타겟",
      killzoneWhatDesc: "마켓 메이커가 과도한 레버리지 트레이더를 사냥하는 알고리즘 청산 클러스터.",
      killzoneHowDesc: "절대 시장가로 매수하지 마십시오. 엄청난 할인가에 플래시 크래시를 잡기 위해 이 가격에 정확히 지정가 매수 주문을 하십시오.",
      btcCluster: "BTC 클러스터",
      ethCluster: "ETH 클러스터",
      solCluster: "SOL 클러스터",
      encryptedData: "암호화된 데이터",
      encryptedDesc: "정밀 유동성 타겟이 제한되었습니다.",
      unlockProAccess: "프로 액세스 잠금 해제:",
      feature1: "실시간 BTC, ETH, SOL 킬 존",
      feature2: "기관 다이버전스 알림",
      feature3: "맞춤형 알트코인 레이더",
      radarTitle: "맞춤형 알트코인 레이더",
      proFeature: "프로 기능",
      whaleWatch: "고래 워치",
      disclaimer: "면책 조항: Project ARES는 재정적 조언이 아닌 데이터 합성 도구입니다. 암호화폐 거래는 전액 손실의 위험이 높습니다. 개발자는 이 데이터에 기반한 거래 결정에 대해 책임지지 않습니다.",
      rightsReserved: "© 2026 Project ARES. 모든 권리 보유.",
      termsOfService: "서비스 약관",
      privacyPolicy: "개인정보 처리방침",
      protocolPostureDesc: "광범위한 시장 심리, 기관 흐름, 가격 변동을 합성하여 현재의 거시적 입장을 결정합니다.",
      protocolKillzoneDesc: "BTC, ETH, SOL에서 큰 가격 반응이 예상되는 확률 높은 청산 클러스터 및 핵심 기술적 영역입니다."
    },
    ES: {
      upgradeToPro: "ACTUALIZAR A PRO - $29/MES",
      systemProtocol: "Protocolo del Sistema",
      unlockInstitutional: "Desbloquee datos de flujo institucional y radar de altcoins personalizado",
      iAgree: "Acepto los Términos de Servicio y entiendo que se trata de datos educativos 'tal cual'.",
      methodology: "Metodología",
      fieldManual: "Manual de Campo",
      lastSweep: "Último Escaneo",
      radarStatus: "Síntesis de datos institucionales. No seas liquidez de salida. Opera con las matemáticas.",
      postureTitle: "Postura del Mercado",
      whatItIs: "Qué es:",
      howToUse: "Cómo usar:",
      postureWhatDesc: "El cálculo de la IA del entorno macro basado en flujos institucionales.",
      postureHowDesc: "Verde = Seguro aumentar tamaño de posición. Amarillo = Reducir tamaño. Rojo = Mover a reservas de efectivo pesadas y prepararse para colapsos.",
      intelTitle: "Inteligencia Accionable",
      intelWhatDesc: "Síntesis en tiempo real de los flujos de ETF de Wall Street frente al sentimiento minorista.",
      intelHowDesc: "Lea esto antes de realizar cualquier operación para asegurarse de que está operando junto a las instituciones, no contra ellas.",
      intelAwaiting: "Esperando síntesis cuantitativa...",
      killzoneTitle: "Zonas de Muerte",
      killzoneWhatDesc: "Cúmulos de liquidación algorítmica donde los creadores de mercado cazan a los operadores sobreapalancados.",
      killzoneHowDesc: "NUNCA compre a precio de mercado. Coloque órdenes de compra límite exactamente en estos precios para atrapar caídas repentinas con un descuento masivo.",
      btcCluster: "Grupo BTC",
      ethCluster: "Grupo ETH",
      solCluster: "Grupo SOL",
      encryptedData: "Datos Encriptados",
      encryptedDesc: "Los objetivos precisos de liquidez están restringidos.",
      unlockProAccess: "Desbloquear Acceso Pro:",
      feature1: "Zonas de muerte en vivo de BTC, ETH y SOL",
      feature2: "Alertas de divergencia institucional",
      feature3: "Radar de altcoins personalizado",
      radarTitle: "Radar de Altcoins Personalizado",
      proFeature: "Función Pro",
      whaleWatch: "Vigilancia de Ballenas",
      disclaimer: "DESCARGO DE RESPONSABILIDAD: Project ARES es una herramienta de síntesis de datos, no asesoramiento financiero. El comercio de criptomonedas conlleva un alto riesgo de pérdida total. Los desarrolladores no son responsables de ninguna decisión comercial basada en estos datos.",
      rightsReserved: "© 2026 Project ARES. Todos los derechos reservados.",
      termsOfService: "Términos de Servicio",
      privacyPolicy: "Política de Privacidad",
      protocolPostureDesc: "Sintetiza el sentimiento general del mercado, los flujos institucionales y la acción del precio para determinar la postura macroeconómica actual.",
      protocolKillzoneDesc: "Cúmulos de liquidación de alta probabilidad y zonas técnicas críticas donde se esperan reacciones importantes en los precios de BTC, ETH y SOL."
    },
    JP: {
      upgradeToPro: "プロにアップグレード - 月額$29",
      systemProtocol: "システムプロトコル",
      unlockInstitutional: "機関投資家のフローデータとカスタムアルトコインレーダーのロックを解除",
      iAgree: "利用規約に同意し、これが「現状有姿」の教育データであることを理解します。",
      methodology: "方法論",
      fieldManual: "フィールドマニュアル",
      lastSweep: "最終スキャン",
      radarStatus: "機関データ合成。出口流動性にならないでください。数学で取引してください。",
      postureTitle: "市場態勢",
      whatItIs: "説明：",
      howToUse: "使用方法：",
      postureWhatDesc: "機関のフローに基づくマクロ環境のAI計算。",
      postureHowDesc: "緑 = ポジションサイズの増加は安全。黄 = サイズの縮小。赤 = 大規模な現金準備への移行と暴落への備え。",
      intelTitle: "実行可能な情報",
      intelWhatDesc: "ウォール街のETFフローと個人投資家の心理のリアルタイム合成。",
      intelHowDesc: "機関投資家と反対に取引していないことを確認するため、取引を行う前にこれをお読みください。",
      intelAwaiting: "定量的合成を待機中...",
      killzoneTitle: "キルゾーンターゲット",
      killzoneWhatDesc: "マーケットメーカーが過剰なレバレッジをかけたトレーダーを狩るアルゴリズムの清算クラスター。",
      killzoneHowDesc: "絶対に成行買いしないでください。大幅な割引でフラッシュクラッシュを捉えるため、これらの価格に正確に指値買い注文を出してください。",
      btcCluster: "BTC クラスター",
      ethCluster: "ETH クラスター",
      solCluster: "SOL クラスター",
      encryptedData: "暗号化されたデータ",
      encryptedDesc: "正確な流動性ターゲットは制限されています。",
      unlockProAccess: "プロアクセスをロック解除：",
      feature1: "ライブ BTC、ETH、SOL キルゾーン",
      feature2: "機関ダイバージェンスアラート",
      feature3: "カスタムアルトコインレーダー",
      radarTitle: "カスタムアルトコインレーダー",
      proFeature: "プロ機能",
      whaleWatch: "ホエールウォッチ",
      disclaimer: "免責事項：Project ARESはデータ合成ツールであり、財務アドバイスではありません。暗号資産の取引は全損の高いリスクを伴います。開発者はこのデータに基づく取引決定について責任を負いません。",
      rightsReserved: "© 2026 Project ARES. 全著作権所有。",
      termsOfService: "利用規約",
      privacyPolicy: "プライバシーポリシー",
      protocolPostureDesc: "広範な市場心理、機関のフロー、価格変動を統合して、現在のマクロスタンスを決定します。",
      protocolKillzoneDesc: "BTC、ETH、SOLで大きな価格反応が予想される確率の高い清算クラスターおよび重要な技術ゾーンです。"
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
